### ISSUE TITLE
Python. Function argument indentation

### ISSUE THREAD

**Issue by ANtlord** [yioneko/nvim-yati#7] opened 2022-10-23 16:16 UTC
https://github.com/yioneko/nvim-yati/blob/d3a898e5afd079e1586fe39a45899bf706dfbd12/test/indent/sample.py#L68

Hi

Here is the line with the test case of arguments indentation.  The first argument is on the same line as the function name.  The test breaks if you extend the function name by a couple of symbols.  For example

```python
def very_long_function(a,
                       b,
                       c):
```

The test case doesn't pass, but should according the proposal https://peps.python.org/pep-0008/#indentation

**Comment by yioneko** [comment] 2022-10-30 16:51
Thanks for pointing out, this might be duplicate of #3 and I will try to fix it in the next rewrite.

**Closed as completed by yioneko** 2022-10-30 16:51 UTC
